spring:
  application:
    name: knitting-search-api
  elasticsearch:
    uris: http://localhost:9200

access:
  raverly:
    base_url: ${base_url:https://api.ravelry.com}
    client_id: ${client_id}
    client_secret: ${client_secret}